ssbc/ssb-meta-feeds

- messages.js
- metafeed.js
- package.json
- query.js
- test/messages.js
- test/metafeed.js
- test/query.js
Removed uses of `ssb.db.onDrain()` and `ssb.db.getJITDB()`, as those are internal APIs.
The diff looks crazy, but just because indentation changed, otherwise it's rather simple PR.
> Don't use ssb-db2 internals

- api.js
- messages.js
- test/messages.js
- test/query.js
Follow up to https://github.com/ssb-ngi-pointer/ssb-db2/pull/248, I also changed the API names in `sbot.metafeeds.messages` to make it easier to remember:
- `msgValXXXX()` creates a `msgVal` for content.type `XXXX`
- `contentYYYY()` creates a `content` for type `YYYY`
Meta feed `msgVal`s use `db.add()` not `db.publishAs()`.
> replace publishAs() with add() for bendy butt msgs

- package.json
Simple bump some dependencies. Most important is the db2 so we can remove that branch.
> Bump ssb-db2 & bendy butt

- query.js
Takes SSB URIs for `bendybutt-v1` and `gabbygrove-v1` into account when calculating and assigning the `prefixOffset` for the subfeed `equal()` db2 operator call
In response to: https://github.com/ssb-ngi-pointer/ssb-meta-feeds/issues/38
-----
A question which came up for me while making this PR:
Would it be more efficient (or accurate) to calculate the required `prefixOffset` based on the given `feedId`, rather than using the max length as offset for all cases?
> Update subfeed prefix offset value (account for SSB URIs)

- README.md
- api.js
- query.js
- validate.js
Now that we have a means of validating the `contentSection` of a meta feeds message, we can begin to use it in this module (and others).
I'm beginning by adding a simple check before `sbot.db.add` is called in the `create` function. I believe this results in the validation check being called on three occasions in the current test suite:
`findOrCreate() a sub feed`
`findOrCreate() a sub meta feed`
`findOrCreate() a subfeed under a sub meta feed`
> Integrate validation checks

- README.md
- api.js
- query.js
- test/api.js
- test/query.js
In the new multi-format ssb-ebt we need to be able to get any feedID and infer what is it: is it a classic `main` feed? Is it a `classic` index feed? Is it a bendy butt? (The first 2 questions are the most important) It's not enough to just look at the feedId and infer the `feedformat`, we also need to know the `feedpurpose`. In ssb-replication-scheduler we will also need something like this.
New API `findById()`. Turns out it was already implemented as `getMetadata`, I just did further tweaking in its internals, to:
- If the feedId given to `findById()` has been tombstoned, return `null`
- Infer the `feedformat` from the `feedId`
- Remove msg.value.content stuff such as `type` and `nonce` etc
- Bundle unknown fields in `msg.value.content` under `metadata` object, like it is during …
> introduce findById()

- README.md
- api.js
- feeds-lookup.js
- index.js
- package.json
- query.js
- test/api.js
- test/query.js
Adds `findByIdSync`, similar to `findById`, but synchronous (see e.g. similar to `fs.readFile` and `fs.readFileSync`). The synchronous variant requires calling `loadState(cb)` before usage, otherwise it throws an error.
I also refactored/moved stuff from query.js to feeds-lookup.js.
> add findByIdSync API

- README.md
- api.js
- feeds-lookup.js
- test/api.js
ssb-meta-feeds `findByIdSync` is used in the new ssb-ebt https://github.com/ssbc/ssb-ebt/pull/52 which in turn is used in https://github.com/ssb-ngi-pointer/ssb-replication-scheduler/pull/5 . 
We bumped into a race condition where there are two pull.drains on meta feed messages: **(A)** one in ssb-meta-feeds `feeds-lookup.js` (to keep track of the "details" object associated which each (foreign or local) subfeed ID) and **(B)** another one in `ssb-replication-scheduler` to trigger the replication of a subfeed. We realized that the processing in **(A)** for a specific subfeed ID  **must** happen before the respective processing in **(B)** because information calculated in **(A)** will be needed by ssb-ebt once **(B)** calls into ssb-ebt APIs.
New API `ensureLoaded(feedId, cb)` similar to …
> new API ensureLoaded()

- feeds-lookup.js
- test/api.js
This one slipped through. For consistency, we should use `classic` everywhere in this module.
> rename one "ed25519" to "classic"

- README.md
- api.js
- feeds-lookup.js
- package.json
- test/api.js
> new API branchStream()

- api.js
Here's something nice I bumped into.
If the root meta feed has already been fetched (from disk) or created, then we can just store it in memory, in the lock. This should be an optimization because it prevents subsequent calls to look it up from the disk.
(Actually, now that I'm typing this, I'm not sure if this is worthwhile optimization. ssb-db2 and jitdb seem to have quite a good amount of caching already. Feel free to say no to this PR)
> cache the root meta feed in memory

- README.md
- api.js
- feeds-lookup.js
- query.js
- test/api.js
- test/validate.js
So, I began by thinking how to make `find(metafeed, visit, cb)` be usable for foreign peers. It wasn't so obvious, because `find` could be used in so many ways:
- `find(null, null, cb)` to get your own root mf
- `find(myRoot, visit, cb)` to get my own subfeeds
- `find(somethingConfusing, visit, cb)` to get foreign subfeeds
In the third case, what if you just wanted to pass a `visit` function and you don't care about the 1st arg? That seems ambiguous because if the 1st arg is null, it means you want to find something that you own. And actually `find(null, null, cb)` is also ambiguous because it looks like you want to get *any* subfeed.
----
So I side stepped this whole headache when I realized that `branchStream` can already be used as an API to find any subfeeds. You just need to use …
> hard deprecate find() and filter()

- api.js
- feeds-lookup.js
- package.json
- test/api.js
We only used `loadState`, `ensureLoaded`, and `findByIdSync` in ssb-ebt, but after [this refactor](https://github.com/ssbc/ssb-ebt/pull/71/files) (merged and published), we don't need these anymore.
Should make it overall easier to work on this module if it has less code.
> remove unused APIs ensureLoaded, findByIdSync, loadState

- README.md
- api.js
- lookup.js
- messages.js
- package.json
- query.js
- test/api/advanced/find-by-id.test.js
- test/api/advanced/find-or-create.test.js
- test/testtools.js
Cases this has to cover:
1. :x: `recp = sbot.id`
- this is technically an "own_secret" case, but we will hit bumps because ssb-box2 doesn't know about meta-feeds, and "own" now being many keys
- on encrption, I _think_ box2 will see this as own-encrypt?
- on decrypt, box2 will almost certainly NOT try own keys
2. :heavy_check_mark:  `recps = groupId`
- this case should be fine... as we try group keys on all our messages
3. :x: `recp = someFeedId`
- this is the DM case, so the shared key should be derived from shardFeedId (author) + someFeedId
- this should "just work"
4. :x: `recp = POBoxId`
:x: = this PR doesn't handle, and has test cases showing they explicitly callback with an error
> encrypted metafeed API (AGAIN)

- api.js
- package.json
- test/api/find-and-tombstone.test.js
- test/api/find-or-create.test.js
I'm working on updating ssb-replication-scheduler to use the new API in ssb-meta-feeds, and in the tests there are some cases of index feeds that are created at the same time.
If two `findOrCreate` calls happen concurrently ("at the same time"), then both calls may create a "v1" feed under the root, which leads to a situation like
```mermaid
graph TB;
root --> v1a[v1] & v1b[v1]
```
This can also happen with shard feeds and leaf feeds.
Also, this concurrency problem can happen with `findAndTombstone`: there should be only one `metafeed/tombstone` message for a given subfeed.
Use `mutexify` in `findOrCreate` and `findAndTombstone` to enforce that only one call can happen at a time. I was working on a more complex solution before, which would *allow* concurrency if you're creating unrelated …
> ensure that findOrCreate / findAndTombstone is never concurrent

- api.js
- test/api/find-or-create.test.js
As the README says.
First commit introduces test that reproduces the bug, the second commit introduces the fix that makes the test pass. Also known as the "1st :x: 2nd :heavy_check_mark:" pattern.
> findOrCreate without details should give root

- api.js
- package.json
- test/api/advanced/find-and-tombstone.test.js
- test/api/advanced/find-by-id.test.js
- test/api/advanced/find-or-create.test.js
- test/api/branch-stream.test.js
- test/api/find-or-create.test.js
I'm working on ssb-replication-scheduler to make it understand the v1 tree structure, and it expects all feeds to be in paths `root/v1/:shard/___`.
ssb-meta-feeds was still doing `root/main`. See also https://github.com/ssbc/ssb-meta-feeds-spec/issues/35
When the root metafeed is created, publish the main as a `metafeed/add/existing` under `root/v1/:shard/main`.
> main located at root/v1/:shard/main branch

- README.md
- README_ADVANCED.md
- api.js
- constants.js
- lookup.js
- query.js
- test/api/advanced/find-and-tombstone.test.js
- test/api/advanced/find-by-id.test.js
- test/api/advanced/find-or-create.test.js
- test/api/advanced/get-root.test.js
- test/api/branch-stream.test.js
- test/api/find-and-tombstone.test.js
- test/api/find-or-create.test.js
- test/query.test.js
- test/testtools.js
There are a couple legacy decisions in this library that are still haunting us. Like `feedpurpose` instead of `purpose`, it's cemented in the spec and not worth changing it. But also `details.subfeed`. The worst is when `details` refers to the root metafeed, and thus `details.subfeed` is the **id of the root metafeed**. Disgusting! Someone will definitely feel confused by this API.
Also, the branches as tuples `[id, details]` was getting really obnoxious to work with, when it could just be `details.id` etc.
We can keep the spec untouched while making this library return more reasonable.
- `details.metafeed` => `details.parent`
- `details.subfeed` => `details.id`
- `details.feedpurpose` => `details.purpose`
- `details.feedformat` => `details.feedFormat` (this one can't be `format` because …
> tidy the API results

- api.js
- test/api/find-and-tombstone.test.js
My tests in ssb-replication-scheduler were failing on findAndTombstone
There are two problems:
1. `feedformat` is supposed to be `feedFormat`
2. findAndTombstone mutates the input `details` to add `.feedformat` to it, so if you pass the same `details` object (like our tests do), it'll work, but if you pass two different objects that are deep equal, it won't work
Rename `feedformat` to `feedFormat` and don't mutate the inputs.
> fix findAndTombstone to not use mutation

- README.md
- api.js
- lookup.js
- package.json
- test/api/tree.test.js
For fun. I also thought that `printTree` could be very useful in the future when debugging.
`printTree()` will put this kind of ASCII diagram in the console:
```
root
└─┬ v1
├─┬ 2
│ └── main
└─┬ f
└── chess
```
`getTree()` will return an object that has the full hierarchical structure for the tree. This could be a good alternative to `branchStream` for some downstream modules. 
The new dependency [has a tiny footprint](https://bundlephobia.com/package/print-tree@0.1.5).
> add getTree and printTree APIs

- api.js
- lookup.js
- test/api/branch-stream.test.js
- test/api/find-or-create.test.js
Tests were failing downstream in ssb-tribes2 when I created a groupFeed and then tried to use branchStream to replicate that to other peers.
After findOrCreate, branchStream had to "wait" for the ssb-db2 bendybutt message to be processed *and then* converted to a "details" object.
If you called branchStream immediately after findOrCreate was done, this means you would miss the newly-created leaf feed.
As soon as findOrCreate is done, `updateLookup` on the branchStream logic so that the data is synchronously available there.
> branchStream can be called immediately after findOrCreate

- README.md
- api.js
- lookup.js
- query.js
- test/api/branch-stream.test.js
In ssb-box2 we're going to have to traverse "my" metafeed tree, and then match that with other peers' metafeed tree to create DH keys.
When using default branchStream, it returns any branch in the "forest" (the collection of all trees), and there isn't any way how we can know whether a branch belongs to _my_ tree, or some _other_ peer's tree.
Add `.keys` field for all feed details returned by branchStream if I own that feed. If `details.keys` exists, it means you own the subfeed (well, by definition, because if you have the `keys`, you can publish to that feed). 
In the implementation, this requires loading our `seed` before querying ssb-db2 for messages that build up the branches lookup data structure. We also load the root metafeed keys in that data structure ASAP, so that whenever we …
> add .keys to all feed details you own

- FeedDetails.js
- api.js
- lookup.js
- query.js
- test/api/advanced/find-and-tombstone.test.js
- test/api/advanced/find-by-id.test.js
- test/query.test.js
This is not a necessary addition, it's a nice-to-have addition.
I was thinking how we return `{ id, parent, purpose, ... }` objects in a bunch of places, and it's getting kind of out of hand. Several different files are creating/updating these objects, and they *have* to follow the same shape, but we're not enforcing the same shape.
Moreover, I'm also thinking that there will be many of these objects, because each branch in `branchStream` has many of these. It will be better to profile memory usage if we use classes, because they show up immediately in the Chrome DevTools. Also, it helps the V8 optimizer if all of the objects share exactly the same shape (same set of `Object.keys()` always) because then under the hood it creates a hidden `struct` (in C) to back all these objects.
You …
> introduce FeedDetails class

- test/api/find-and-tombstone.test.js
The tests were using an outdated branchStream API shape and just happened to pass.
> fix findAndTombstone tests

- FeedDetails.js
- test/FeedDetails.test.js
I got some weird duplicate branches coming out of `branchStream`, and it turned out that the '.equals()' function wasn't working here:
https://github.com/ssbc/ssb-meta-feeds/blob/895781aa18d789d79600020119bb22150061ef3a/lookup.js#L134
`FeedDetails`'s `equals()` is too simplistic, it's comparing two buffers with `===`, and it's comparing two objects (`keys`) with `===` too.
Compare buffers with `Buffer.equals` and compare objects with fast-deep-equal.
> Fix FeedDetails.equals to compare buffers correctly

- lookup.js
- test/api/branch-stream.test.js
https://github.com/ssbc/ssb-meta-feeds/pull/110#discussion_r1023762878
If you call branchStream with live first, and then immediately call branchStream with old second, then the second one will just assume that the state has loaded, without actually waiting for it.
Just a bit of booleans and some ifs.
> fix branchStream "loadState" logic

- lookup.js
- test/api/branch-stream.test.js
- test/testbot.js
I'm working on putting 2b funky recps in ssb-tribes2, and noticed a race condition in the tests.
There's a race condition between:
1. Replicate the shard feed that announces (encrypted!) a group feed
2. Replicate the `group/add-member` message (on the invitations feed) that allows us to decrypt (1)
Ideally, (2) happens first and then (1), but if (1) happens first we have a problem. Even though ssb-tribes2 will run reindexEncrypted() when it bumps into a `group/add-member` msg, the `branchStream()` in ssb-meta-feeds won't know that it has to "restart". It just stays stuck in live mode, and of course there are no "new" messages. We only have old messages that were decrypted.
This is not an ideal solution, but it works. I have an idea for the ideal case, which would be a new API in ssb-db2 …
> fix branchStream to restart after box2 decryption
