.prettierrc
index.js
keys.js
messages.js
metafeed.js
package.json
query.js
test/keys.js
test/messages.js
test/metafeed.js
test/query.js

Same as in `jitdb`, `ssb-bfe`, `ssb-bendy-butt`, etc.

apply prettier for code formatting

---

messages.js
package.json

Uses `encodeNew` for instance.

update ssb-bendy-butt and db2

---

messages.js
package.json
query.js
test/messages.js
test/query.js

Bundled two changes into 1 PR. Sorry ;)
The nonce is the recent change to just embed it directly as a buffer since we have a binary format and the second I stumbled upon where the tombstone message was incorrect.

Fix nonce & tombstone message + query

---

keys.js
messages.js
metafeed.js
package.json
query.js
test/metafeed.js

Easiest to review commit-by-commit.

Small refactors

---

test/api.js

Related to #19 but shouldn't close #19

hacky fix for race condition in tests

---

messages.js
test/api.js

1st commit tests :x:, 2nd commit fixes :heavy_check_mark:

test that we can create a sub meta feed

---

messages.js
query.js
test/api.js

1st test :x:, 2nd fix :heavy_check_mark:

Support creating sub sub feeds

---

messages.js
query.js
test/messages.js

Related to https://github.com/ssb-ngi-pointer/ssb-meta-feed-spec/issues/22
1st test :x: , 2nd fix :heavy_check_mark:

Adding existing feed should have no nonce

---

messages.js
query.js

Here it is, the missing PR. Turns out I had pushed this branch before I formatted my computer's disk.

change metafeed/add to its two subtypes

---

api.js

I was gonna review #30 by suggesting dropping `waitingRootMetaKey`, and then I found a couple other things, so it was easier to make a PR for the PR. :)

refactor rootMetaFeedLock

---

api.js
package.json

Should fix #29. Gonna test it now.

Fix rootmeta concurrency

---

query.js
test/query.js

Add failing hydrated seed test

---

keys.js
messages.js
package.json
query.js
test/api.js
test/keys.js
test/messages.js
test/query.js

Use SSB URIs

---

feeds-lookup.js
test/api.js

test findById/findByIdSync properly

---

messages.js
validate.js

For issue https://github.com/ssb-ngi-pointer/ssb-meta-feeds-spec/issues/27 part 2

metafeed/announce should have content.subfeed

---

feeds-lookup.js

Dont error on looking up gabbygrove-v1 subfeeds

---

api.js
package.json
test/api.js

`findOrCreate` was not working when encrypting. First commit fails, second fixes.

Fix findOrCreate & recps

---

README.md

recover some explanations on the readme

---

feeds-lookup.js
keys.js
messages.js
package.json
query.js
test/api.js
test/query.js
validate.js

https://github.com/ssbc/ssb-ebt/pull/71 for context

support indexed-v1 feed format

---

test/api.test.js

Your cb tests dropped my persistence testing work.
This PR adds it back in

add persistence tests to api

---

package.json

add test for tape test.only being left in code

---

api.js
constants.js
lookup.js
test/api/advanced/find-or-create.test.js
test/api/find-or-create.test.js

Does this one simple thing.
Supercedes: https://github.com/ssbc/ssb-meta-feeds/pull/77

prevent use of protected metadata fields

---

messages.js
package.json
test/api/advanced/find-or-create.test.js
test/api/branch-stream.test.js
test/testbot.js

Depends on : https://github.com/ssbc/ssb-db2/pull/397

ensure not box1 dependant

---

README.md

Ran into this problem while testing replication scheduler

Bendy butt is a requirement

---

FeedDetails.js

Not sure if the real problem is that messages come in out of order, but at least wanted to flag that this function should update parent in any case to be safe.
See this one for details: https://github.com/ssbc/ssb-meta-feeds/issues/117

Make sure FeedDetails.update also updates parent

---

.github/workflows/node.js.yml
api.js
lookup.js
query.js
test/api/find-root-feed-id.test.js

merges into https://github.com/ssbc/ssb-meta-feeds/pull/119

add isRootFeedId, use in findRootFeedById
